spring:
  data:
    elasticsearch:
      # Defaults to cluster-name 'elasticsearch'
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      properties:
        # https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html
        client.transport.ignore_cluster_name: true

swagger:
  customer:
    id: The database generated mobile subscription ID
    first-name: The first name of the customer
    last-name: The last name of the customer
  subscription:
    id: The database generated mobile subscription ID
    msisdn: The mobile number of the subscription
    owner: The owner of the mobile subscription
    user: The user of the mobile subscription
    type: The service type of the mobile subscription
    start-date: The start date of the mobile subscription
  sub-controller:
    create:
      value: Create new mobile subscription
      param: Mobile Subscription information for a new subscription to be created
    get:
      value: Get mobile subscription
      param: Id of the mobile subscription
    get-all:
      value: Get all mobile subscriptions
      param: pageable params
    search:
      value: Search mobile subscriptions by mobile number
      param: Query to search mobile numbers
    update:
      owner:
        value: Update owner of Mobile Subscription
        param: Mobile subscription with owner info to update
        id: Id of the mobile subscription
      user:
        value: Update user of Mobile Subscription
        param: Mobile subscription with user info to update
        id: Id of the mobile subscription
    update-type:
      value: Update service type of Mobile Subscription
      param: Type of the mobile subscription to update
      id: Id of the mobile subscription
    delete:
      value: Delete mobile subscription
      id: Id of the mobile subscription

server:
  port: 8095




